// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/account.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

@com.google.protobuf.Generated
public final class Account extends com.google.protobuf.GeneratedFile {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_PingRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_PingRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_PingResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_PingResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_ReportMatchResultRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_ReportMatchResultRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_ReportMatchResultResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_ReportMatchResultResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 35,
                /* patch= */ 1,
                /* suffix= */ "",
                "Account");
    }

    static {
        java.lang.String[] descriptorData = {
                "\n\034match_arena/v1/account.proto\022\016match_ar" +
                        "ena.v1\"\'\n\013PingRequest\022\030\n\007message\030\001 \001(\tR\007" +
                        "message\"(\n\014PingResponse\022\030\n\007message\030\001 \001(\t" +
                        "R\007message\"9\n\030ReportMatchResultRequest\022\035\n" +
                        "\nsession_id\030\001 \001(\tR\tsessionId\"5\n\031ReportMa" +
                        "tchResultResponse\022\030\n\007success\030\001 \001(\010R\007succ" +
                        "ess2\303\001\n\024AccountLookupService\022A\n\004Ping\022\033.m" +
                        "atch_arena.v1.PingRequest\032\034.match_arena." +
                        "v1.PingResponse\022h\n\021ReportMatchResult\022(.m" +
                        "atch_arena.v1.ReportMatchResultRequest\032)" +
                        ".match_arena.v1.ReportMatchResultRespons" +
                        "eBt\n\026com.matcharena.grpc.v1P\001ZXgithub.co" +
                        "m/ihsanguldur/match-arena/game-service/i" +
                        "nternal/gen/match_arena/v1;matcharenav1b" +
                        "\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_match_arena_v1_PingRequest_descriptor =
                getDescriptor().getMessageType(0);
        internal_static_match_arena_v1_PingRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_PingRequest_descriptor,
                new java.lang.String[]{"Message",});
        internal_static_match_arena_v1_PingResponse_descriptor =
                getDescriptor().getMessageType(1);
        internal_static_match_arena_v1_PingResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_PingResponse_descriptor,
                new java.lang.String[]{"Message",});
        internal_static_match_arena_v1_ReportMatchResultRequest_descriptor =
                getDescriptor().getMessageType(2);
        internal_static_match_arena_v1_ReportMatchResultRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_ReportMatchResultRequest_descriptor,
                new java.lang.String[]{"SessionId",});
        internal_static_match_arena_v1_ReportMatchResultResponse_descriptor =
                getDescriptor().getMessageType(3);
        internal_static_match_arena_v1_ReportMatchResultResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_ReportMatchResultResponse_descriptor,
                new java.lang.String[]{"Success",});
        descriptor.resolveAllFeaturesImmutable();
    }
    private Account() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
