// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/matchmaking.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

@com.google.protobuf.Generated
public interface JoinQueueUpdateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:match_arena.v1.JoinQueueUpdate)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return Whether the queueTicketId field is set.
     */
    boolean hasQueueTicketId();

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return The queueTicketId.
     */
    java.lang.String getQueueTicketId();

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return The bytes for queueTicketId.
     */
    com.google.protobuf.ByteString
    getQueueTicketIdBytes();

    /**
     * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
     *
     * @return Whether the matchFound field is set.
     */
    boolean hasMatchFound();

    /**
     * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
     *
     * @return The matchFound.
     */
    com.matcharena.grpc.v1.MatchFound getMatchFound();

    /**
     * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
     */
    com.matcharena.grpc.v1.MatchFoundOrBuilder getMatchFoundOrBuilder();

    com.matcharena.grpc.v1.JoinQueueUpdate.UpdateCase getUpdateCase();
}
