// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/matchmaking.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

/**
 * Protobuf type {@code match_arena.v1.JoinQueueUpdate}
 */
@com.google.protobuf.Generated
public final class JoinQueueUpdate extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:match_arena.v1.JoinQueueUpdate)
        JoinQueueUpdateOrBuilder {
    public static final int QUEUE_TICKET_ID_FIELD_NUMBER = 1;
    public static final int MATCH_FOUND_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:match_arena.v1.JoinQueueUpdate)
    private static final com.matcharena.grpc.v1.JoinQueueUpdate DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<JoinQueueUpdate>
            PARSER = new com.google.protobuf.AbstractParser<JoinQueueUpdate>() {
        @java.lang.Override
        public JoinQueueUpdate parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 35,
                /* patch= */ 1,
                /* suffix= */ "",
                "JoinQueueUpdate");
    }

    static {
        DEFAULT_INSTANCE = new com.matcharena.grpc.v1.JoinQueueUpdate();
    }

    private int updateCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object update_;
    private byte memoizedIsInitialized = -1;

    ;

    // Use JoinQueueUpdate.newBuilder() to construct.
    private JoinQueueUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private JoinQueueUpdate() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueUpdate_descriptor;
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.matcharena.grpc.v1.JoinQueueUpdate prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.matcharena.grpc.v1.JoinQueueUpdate getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<JoinQueueUpdate> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueUpdate_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.matcharena.grpc.v1.JoinQueueUpdate.class, com.matcharena.grpc.v1.JoinQueueUpdate.Builder.class);
    }

    public UpdateCase
    getUpdateCase() {
        return UpdateCase.forNumber(
                updateCase_);
    }

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return Whether the queueTicketId field is set.
     */
    public boolean hasQueueTicketId() {
        return updateCase_ == 1;
    }

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return The queueTicketId.
     */
    public java.lang.String getQueueTicketId() {
        if (updateCase_ != 1) {
            return "";
        }
        java.lang.Object ref = update_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            update_ = s;
            return s;
        }
    }

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return The bytes for queueTicketId.
     */
    public com.google.protobuf.ByteString
    getQueueTicketIdBytes() {
        if (updateCase_ != 1) {
            return com.google.protobuf.ByteString.copyFromUtf8("");
        }
        java.lang.Object ref = update_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            update_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
     *
     * @return Whether the matchFound field is set.
     */
    @java.lang.Override
    public boolean hasMatchFound() {
        return updateCase_ == 2;
    }

    /**
     * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
     *
     * @return The matchFound.
     */
    @java.lang.Override
    public com.matcharena.grpc.v1.MatchFound getMatchFound() {
        if (updateCase_ == 2) {
            return (com.matcharena.grpc.v1.MatchFound) update_;
        }
        return com.matcharena.grpc.v1.MatchFound.getDefaultInstance();
    }

    /**
     * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
     */
    @java.lang.Override
    public com.matcharena.grpc.v1.MatchFoundOrBuilder getMatchFoundOrBuilder() {
        if (updateCase_ == 2) {
            return (com.matcharena.grpc.v1.MatchFound) update_;
        }
        return com.matcharena.grpc.v1.MatchFound.getDefaultInstance();
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (updateCase_ == 1) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, update_);
        }
        if (updateCase_ == 2) {
            output.writeMessage(2, (com.matcharena.grpc.v1.MatchFound) update_);
        }
        getUnknownFields().writeTo(output);
    }

    private int computeSerializedSize_0() {
        int size = 0;
        if (updateCase_ == 1) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, update_);
        }
        if (updateCase_ == 2) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, (com.matcharena.grpc.v1.MatchFound) update_);
        }
        return size;
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += computeSerializedSize_0();
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.matcharena.grpc.v1.JoinQueueUpdate)) {
            return super.equals(obj);
        }
        com.matcharena.grpc.v1.JoinQueueUpdate other = (com.matcharena.grpc.v1.JoinQueueUpdate) obj;

        if (!getUpdateCase().equals(other.getUpdateCase())) return false;
        switch (updateCase_) {
            case 1:
                if (!getQueueTicketId()
                        .equals(other.getQueueTicketId())) return false;
                break;
            case 2:
                if (!getMatchFound()
                        .equals(other.getMatchFound())) return false;
                break;
            case 0:
            default:
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (updateCase_) {
            case 1:
                hash = (37 * hash) + QUEUE_TICKET_ID_FIELD_NUMBER;
                hash = (53 * hash) + getQueueTicketId().hashCode();
                break;
            case 2:
                hash = (37 * hash) + MATCH_FOUND_FIELD_NUMBER;
                hash = (53 * hash) + getMatchFound().hashCode();
                break;
            case 0:
            default:
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JoinQueueUpdate> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.JoinQueueUpdate getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    public enum UpdateCase
            implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
        QUEUE_TICKET_ID(1),
        MATCH_FOUND(2),
        UPDATE_NOT_SET(0);
        private final int value;

        private UpdateCase(int value) {
            this.value = value;
        }

        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static UpdateCase valueOf(int value) {
            return forNumber(value);
        }

        public static UpdateCase forNumber(int value) {
            switch (value) {
                case 1:
                    return QUEUE_TICKET_ID;
                case 2:
                    return MATCH_FOUND;
                case 0:
                    return UPDATE_NOT_SET;
                default:
                    return null;
            }
        }

        public int getNumber() {
            return this.value;
        }
    }

    /**
     * Protobuf type {@code match_arena.v1.JoinQueueUpdate}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:match_arena.v1.JoinQueueUpdate)
            com.matcharena.grpc.v1.JoinQueueUpdateOrBuilder {
        private int updateCase_ = 0;
        private java.lang.Object update_;
        private int bitField0_;
        private com.google.protobuf.SingleFieldBuilder<
                com.matcharena.grpc.v1.MatchFound, com.matcharena.grpc.v1.MatchFound.Builder, com.matcharena.grpc.v1.MatchFoundOrBuilder> matchFoundBuilder_;

        // Construct using com.matcharena.grpc.v1.JoinQueueUpdate.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueUpdate_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueUpdate_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.matcharena.grpc.v1.JoinQueueUpdate.class, com.matcharena.grpc.v1.JoinQueueUpdate.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            if (matchFoundBuilder_ != null) {
                matchFoundBuilder_.clear();
            }
            updateCase_ = 0;
            update_ = null;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueUpdate_descriptor;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.JoinQueueUpdate getDefaultInstanceForType() {
            return com.matcharena.grpc.v1.JoinQueueUpdate.getDefaultInstance();
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.JoinQueueUpdate build() {
            com.matcharena.grpc.v1.JoinQueueUpdate result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.JoinQueueUpdate buildPartial() {
            com.matcharena.grpc.v1.JoinQueueUpdate result = new com.matcharena.grpc.v1.JoinQueueUpdate(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            buildPartialOneofs(result);
            onBuilt();
            return result;
        }

        private void buildPartial0(com.matcharena.grpc.v1.JoinQueueUpdate result) {
            int from_bitField0_ = bitField0_;
        }

        private void buildPartialOneofs(com.matcharena.grpc.v1.JoinQueueUpdate result) {
            result.updateCase_ = updateCase_;
            result.update_ = this.update_;
            if (updateCase_ == 2 &&
                    matchFoundBuilder_ != null) {
                result.update_ = matchFoundBuilder_.build();
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.matcharena.grpc.v1.JoinQueueUpdate) {
                return mergeFrom((com.matcharena.grpc.v1.JoinQueueUpdate) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.matcharena.grpc.v1.JoinQueueUpdate other) {
            if (other == com.matcharena.grpc.v1.JoinQueueUpdate.getDefaultInstance()) return this;
            switch (other.getUpdateCase()) {
                case QUEUE_TICKET_ID: {
                    updateCase_ = 1;
                    update_ = other.update_;
                    onChanged();
                    break;
                }
                case MATCH_FOUND: {
                    mergeMatchFound(other.getMatchFound());
                    break;
                }
                case UPDATE_NOT_SET: {
                    break;
                }
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            updateCase_ = 1;
                            update_ = input.readStringRequireUtf8();
                            break;
                        } // case 10
                        case 18: {
                            input.readMessage(
                                    internalGetMatchFoundFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            updateCase_ = 2;
                            break;
                        } // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        public UpdateCase
        getUpdateCase() {
            return UpdateCase.forNumber(
                    updateCase_);
        }

        public Builder clearUpdate() {
            updateCase_ = 0;
            update_ = null;
            onChanged();
            return this;
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @return Whether the queueTicketId field is set.
         */
        @java.lang.Override
        public boolean hasQueueTicketId() {
            return updateCase_ == 1;
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @return The queueTicketId.
         */
        @java.lang.Override
        public java.lang.String getQueueTicketId() {
            if (updateCase_ != 1) {
                return "";
            }
            java.lang.Object ref = update_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                update_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @param value The queueTicketId to set.
         * @return This builder for chaining.
         */
        public Builder setQueueTicketId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            updateCase_ = 1;
            update_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @return The bytes for queueTicketId.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getQueueTicketIdBytes() {
            if (updateCase_ != 1) {
                return com.google.protobuf.ByteString.copyFromUtf8("");
            }
            java.lang.Object ref = update_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                update_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @param value The bytes for queueTicketId to set.
         * @return This builder for chaining.
         */
        public Builder setQueueTicketIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            updateCase_ = 1;
            update_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearQueueTicketId() {
            if (updateCase_ == 1) {
                updateCase_ = 0;
                update_ = null;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         *
         * @return Whether the matchFound field is set.
         */
        @java.lang.Override
        public boolean hasMatchFound() {
            return updateCase_ == 2;
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         *
         * @return The matchFound.
         */
        @java.lang.Override
        public com.matcharena.grpc.v1.MatchFound getMatchFound() {
            if (matchFoundBuilder_ == null) {
                if (updateCase_ == 2) {
                    return (com.matcharena.grpc.v1.MatchFound) update_;
                }
                return com.matcharena.grpc.v1.MatchFound.getDefaultInstance();
            } else {
                if (updateCase_ == 2) {
                    return matchFoundBuilder_.getMessage();
                }
                return com.matcharena.grpc.v1.MatchFound.getDefaultInstance();
            }
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         */
        public Builder setMatchFound(com.matcharena.grpc.v1.MatchFound value) {
            if (matchFoundBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                update_ = value;
                onChanged();
            } else {
                matchFoundBuilder_.setMessage(value);
            }
            updateCase_ = 2;
            return this;
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         */
        public Builder setMatchFound(
                com.matcharena.grpc.v1.MatchFound.Builder builderForValue) {
            if (matchFoundBuilder_ == null) {
                update_ = builderForValue.build();
                onChanged();
            } else {
                matchFoundBuilder_.setMessage(builderForValue.build());
            }
            updateCase_ = 2;
            return this;
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         */
        public Builder mergeMatchFound(com.matcharena.grpc.v1.MatchFound value) {
            if (matchFoundBuilder_ == null) {
                if (updateCase_ == 2 &&
                        update_ != com.matcharena.grpc.v1.MatchFound.getDefaultInstance()) {
                    update_ = com.matcharena.grpc.v1.MatchFound.newBuilder((com.matcharena.grpc.v1.MatchFound) update_)
                            .mergeFrom(value).buildPartial();
                } else {
                    update_ = value;
                }
                onChanged();
            } else {
                if (updateCase_ == 2) {
                    matchFoundBuilder_.mergeFrom(value);
                } else {
                    matchFoundBuilder_.setMessage(value);
                }
            }
            updateCase_ = 2;
            return this;
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         */
        public Builder clearMatchFound() {
            if (matchFoundBuilder_ == null) {
                if (updateCase_ == 2) {
                    updateCase_ = 0;
                    update_ = null;
                    onChanged();
                }
            } else {
                if (updateCase_ == 2) {
                    updateCase_ = 0;
                    update_ = null;
                }
                matchFoundBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         */
        public com.matcharena.grpc.v1.MatchFound.Builder getMatchFoundBuilder() {
            return internalGetMatchFoundFieldBuilder().getBuilder();
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         */
        @java.lang.Override
        public com.matcharena.grpc.v1.MatchFoundOrBuilder getMatchFoundOrBuilder() {
            if ((updateCase_ == 2) && (matchFoundBuilder_ != null)) {
                return matchFoundBuilder_.getMessageOrBuilder();
            } else {
                if (updateCase_ == 2) {
                    return (com.matcharena.grpc.v1.MatchFound) update_;
                }
                return com.matcharena.grpc.v1.MatchFound.getDefaultInstance();
            }
        }

        /**
         * <code>.match_arena.v1.MatchFound match_found = 2 [json_name = "matchFound"];</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
                com.matcharena.grpc.v1.MatchFound, com.matcharena.grpc.v1.MatchFound.Builder, com.matcharena.grpc.v1.MatchFoundOrBuilder>
        internalGetMatchFoundFieldBuilder() {
            if (matchFoundBuilder_ == null) {
                if (!(updateCase_ == 2)) {
                    update_ = com.matcharena.grpc.v1.MatchFound.getDefaultInstance();
                }
                matchFoundBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                        com.matcharena.grpc.v1.MatchFound, com.matcharena.grpc.v1.MatchFound.Builder, com.matcharena.grpc.v1.MatchFoundOrBuilder>(
                        (com.matcharena.grpc.v1.MatchFound) update_,
                        getParentForChildren(),
                        isClean());
                update_ = null;
            }
            updateCase_ = 2;
            onChanged();
            return matchFoundBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:match_arena.v1.JoinQueueUpdate)
    }

}

