// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/matchmaking.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

/**
 * Protobuf type {@code match_arena.v1.JoinQueueRequest}
 */
@com.google.protobuf.Generated
public final class JoinQueueRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:match_arena.v1.JoinQueueRequest)
        JoinQueueRequestOrBuilder {
    public static final int PLAYER_ID_FIELD_NUMBER = 1;
    public static final int RATING_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:match_arena.v1.JoinQueueRequest)
    private static final com.matcharena.grpc.v1.JoinQueueRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<JoinQueueRequest>
            PARSER = new com.google.protobuf.AbstractParser<JoinQueueRequest>() {
        @java.lang.Override
        public JoinQueueRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 35,
                /* patch= */ 1,
                /* suffix= */ "",
                "JoinQueueRequest");
    }

    static {
        DEFAULT_INSTANCE = new com.matcharena.grpc.v1.JoinQueueRequest();
    }

    @SuppressWarnings("serial")
    private volatile java.lang.Object playerId_ = "";
    private int rating_ = 0;
    private byte memoizedIsInitialized = -1;

    // Use JoinQueueRequest.newBuilder() to construct.
    private JoinQueueRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private JoinQueueRequest() {
        playerId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueRequest_descriptor;
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.matcharena.grpc.v1.JoinQueueRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.matcharena.grpc.v1.JoinQueueRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<JoinQueueRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.matcharena.grpc.v1.JoinQueueRequest.class, com.matcharena.grpc.v1.JoinQueueRequest.Builder.class);
    }

    /**
     * <code>string player_id = 1 [json_name = "playerId"];</code>
     *
     * @return The playerId.
     */
    @java.lang.Override
    public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            playerId_ = s;
            return s;
        }
    }

    /**
     * <code>string player_id = 1 [json_name = "playerId"];</code>
     *
     * @return The bytes for playerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            playerId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>int32 rating = 2 [json_name = "rating"];</code>
     *
     * @return The rating.
     */
    @java.lang.Override
    public int getRating() {
        return rating_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, playerId_);
        }
        if (rating_ != 0) {
            output.writeInt32(2, rating_);
        }
        getUnknownFields().writeTo(output);
    }

    private int computeSerializedSize_0() {
        int size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerId_);
        }
        if (rating_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, rating_);
        }
        return size;
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += computeSerializedSize_0();
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.matcharena.grpc.v1.JoinQueueRequest)) {
            return super.equals(obj);
        }
        com.matcharena.grpc.v1.JoinQueueRequest other = (com.matcharena.grpc.v1.JoinQueueRequest) obj;

        if (!getPlayerId()
                .equals(other.getPlayerId())) return false;
        if (getRating()
                != other.getRating()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PLAYER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getPlayerId().hashCode();
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + getRating();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JoinQueueRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.JoinQueueRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code match_arena.v1.JoinQueueRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:match_arena.v1.JoinQueueRequest)
            com.matcharena.grpc.v1.JoinQueueRequestOrBuilder {
        private int bitField0_;
        private java.lang.Object playerId_ = "";
        private int rating_;

        // Construct using com.matcharena.grpc.v1.JoinQueueRequest.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.matcharena.grpc.v1.JoinQueueRequest.class, com.matcharena.grpc.v1.JoinQueueRequest.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            playerId_ = "";
            rating_ = 0;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_JoinQueueRequest_descriptor;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.JoinQueueRequest getDefaultInstanceForType() {
            return com.matcharena.grpc.v1.JoinQueueRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.JoinQueueRequest build() {
            com.matcharena.grpc.v1.JoinQueueRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.JoinQueueRequest buildPartial() {
            com.matcharena.grpc.v1.JoinQueueRequest result = new com.matcharena.grpc.v1.JoinQueueRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.matcharena.grpc.v1.JoinQueueRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.playerId_ = playerId_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.rating_ = rating_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.matcharena.grpc.v1.JoinQueueRequest) {
                return mergeFrom((com.matcharena.grpc.v1.JoinQueueRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.matcharena.grpc.v1.JoinQueueRequest other) {
            if (other == com.matcharena.grpc.v1.JoinQueueRequest.getDefaultInstance()) return this;
            if (!other.getPlayerId().isEmpty()) {
                playerId_ = other.playerId_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (other.getRating() != 0) {
                setRating(other.getRating());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            playerId_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 16: {
                            rating_ = input.readInt32();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>string player_id = 1 [json_name = "playerId"];</code>
         *
         * @return The playerId.
         */
        public java.lang.String getPlayerId() {
            java.lang.Object ref = playerId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                playerId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string player_id = 1 [json_name = "playerId"];</code>
         *
         * @param value The playerId to set.
         * @return This builder for chaining.
         */
        public Builder setPlayerId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            playerId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string player_id = 1 [json_name = "playerId"];</code>
         *
         * @return The bytes for playerId.
         */
        public com.google.protobuf.ByteString
        getPlayerIdBytes() {
            java.lang.Object ref = playerId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                playerId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string player_id = 1 [json_name = "playerId"];</code>
         *
         * @param value The bytes for playerId to set.
         * @return This builder for chaining.
         */
        public Builder setPlayerIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            playerId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string player_id = 1 [json_name = "playerId"];</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPlayerId() {
            playerId_ = getDefaultInstance().getPlayerId();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>int32 rating = 2 [json_name = "rating"];</code>
         *
         * @return The rating.
         */
        @java.lang.Override
        public int getRating() {
            return rating_;
        }

        /**
         * <code>int32 rating = 2 [json_name = "rating"];</code>
         *
         * @param value The rating to set.
         * @return This builder for chaining.
         */
        public Builder setRating(int value) {

            rating_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>int32 rating = 2 [json_name = "rating"];</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRating() {
            bitField0_ = (bitField0_ & ~0x00000002);
            rating_ = 0;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:match_arena.v1.JoinQueueRequest)
    }

}

