// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/matchmaking.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

/**
 * Protobuf type {@code match_arena.v1.LeaveQueueRequest}
 */
@com.google.protobuf.Generated
public final class LeaveQueueRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:match_arena.v1.LeaveQueueRequest)
        LeaveQueueRequestOrBuilder {
    public static final int QUEUE_TICKET_ID_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:match_arena.v1.LeaveQueueRequest)
    private static final com.matcharena.grpc.v1.LeaveQueueRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<LeaveQueueRequest>
            PARSER = new com.google.protobuf.AbstractParser<LeaveQueueRequest>() {
        @java.lang.Override
        public LeaveQueueRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 35,
                /* patch= */ 1,
                /* suffix= */ "",
                "LeaveQueueRequest");
    }

    static {
        DEFAULT_INSTANCE = new com.matcharena.grpc.v1.LeaveQueueRequest();
    }

    @SuppressWarnings("serial")
    private volatile java.lang.Object queueTicketId_ = "";
    private byte memoizedIsInitialized = -1;
    // Use LeaveQueueRequest.newBuilder() to construct.
    private LeaveQueueRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private LeaveQueueRequest() {
        queueTicketId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueRequest_descriptor;
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.matcharena.grpc.v1.LeaveQueueRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.matcharena.grpc.v1.LeaveQueueRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<LeaveQueueRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.matcharena.grpc.v1.LeaveQueueRequest.class, com.matcharena.grpc.v1.LeaveQueueRequest.Builder.class);
    }

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return The queueTicketId.
     */
    @java.lang.Override
    public java.lang.String getQueueTicketId() {
        java.lang.Object ref = queueTicketId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            queueTicketId_ = s;
            return s;
        }
    }

    /**
     * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
     *
     * @return The bytes for queueTicketId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getQueueTicketIdBytes() {
        java.lang.Object ref = queueTicketId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            queueTicketId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueTicketId_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, queueTicketId_);
        }
        getUnknownFields().writeTo(output);
    }

    private int computeSerializedSize_0() {
        int size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(queueTicketId_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, queueTicketId_);
        }
        return size;
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += computeSerializedSize_0();
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.matcharena.grpc.v1.LeaveQueueRequest)) {
            return super.equals(obj);
        }
        com.matcharena.grpc.v1.LeaveQueueRequest other = (com.matcharena.grpc.v1.LeaveQueueRequest) obj;

        if (!getQueueTicketId()
                .equals(other.getQueueTicketId())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + QUEUE_TICKET_ID_FIELD_NUMBER;
        hash = (53 * hash) + getQueueTicketId().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeaveQueueRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.LeaveQueueRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code match_arena.v1.LeaveQueueRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:match_arena.v1.LeaveQueueRequest)
            com.matcharena.grpc.v1.LeaveQueueRequestOrBuilder {
        private int bitField0_;
        private java.lang.Object queueTicketId_ = "";

        // Construct using com.matcharena.grpc.v1.LeaveQueueRequest.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.matcharena.grpc.v1.LeaveQueueRequest.class, com.matcharena.grpc.v1.LeaveQueueRequest.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            queueTicketId_ = "";
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueRequest_descriptor;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.LeaveQueueRequest getDefaultInstanceForType() {
            return com.matcharena.grpc.v1.LeaveQueueRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.LeaveQueueRequest build() {
            com.matcharena.grpc.v1.LeaveQueueRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.LeaveQueueRequest buildPartial() {
            com.matcharena.grpc.v1.LeaveQueueRequest result = new com.matcharena.grpc.v1.LeaveQueueRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.matcharena.grpc.v1.LeaveQueueRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.queueTicketId_ = queueTicketId_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.matcharena.grpc.v1.LeaveQueueRequest) {
                return mergeFrom((com.matcharena.grpc.v1.LeaveQueueRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.matcharena.grpc.v1.LeaveQueueRequest other) {
            if (other == com.matcharena.grpc.v1.LeaveQueueRequest.getDefaultInstance()) return this;
            if (!other.getQueueTicketId().isEmpty()) {
                queueTicketId_ = other.queueTicketId_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            queueTicketId_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @return The queueTicketId.
         */
        public java.lang.String getQueueTicketId() {
            java.lang.Object ref = queueTicketId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                queueTicketId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @param value The queueTicketId to set.
         * @return This builder for chaining.
         */
        public Builder setQueueTicketId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            queueTicketId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @return The bytes for queueTicketId.
         */
        public com.google.protobuf.ByteString
        getQueueTicketIdBytes() {
            java.lang.Object ref = queueTicketId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                queueTicketId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @param value The bytes for queueTicketId to set.
         * @return This builder for chaining.
         */
        public Builder setQueueTicketIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            queueTicketId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string queue_ticket_id = 1 [json_name = "queueTicketId"];</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearQueueTicketId() {
            queueTicketId_ = getDefaultInstance().getQueueTicketId();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:match_arena.v1.LeaveQueueRequest)
    }

}

