// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/matchmaking.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

/**
 * Protobuf type {@code match_arena.v1.LeaveQueueResponse}
 */
@com.google.protobuf.Generated
public final class LeaveQueueResponse extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:match_arena.v1.LeaveQueueResponse)
        LeaveQueueResponseOrBuilder {
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:match_arena.v1.LeaveQueueResponse)
    private static final com.matcharena.grpc.v1.LeaveQueueResponse DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<LeaveQueueResponse>
            PARSER = new com.google.protobuf.AbstractParser<LeaveQueueResponse>() {
        @java.lang.Override
        public LeaveQueueResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 35,
                /* patch= */ 1,
                /* suffix= */ "",
                "LeaveQueueResponse");
    }

    static {
        DEFAULT_INSTANCE = new com.matcharena.grpc.v1.LeaveQueueResponse();
    }

    private boolean success_ = false;
    private byte memoizedIsInitialized = -1;
    // Use LeaveQueueResponse.newBuilder() to construct.
    private LeaveQueueResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private LeaveQueueResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueResponse_descriptor;
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.matcharena.grpc.v1.LeaveQueueResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.matcharena.grpc.v1.LeaveQueueResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<LeaveQueueResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.matcharena.grpc.v1.LeaveQueueResponse.class, com.matcharena.grpc.v1.LeaveQueueResponse.Builder.class);
    }

    /**
     * <code>bool success = 1 [json_name = "success"];</code>
     *
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
        return success_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (success_ != false) {
            output.writeBool(1, success_);
        }
        getUnknownFields().writeTo(output);
    }

    private int computeSerializedSize_0() {
        int size = 0;
        if (success_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(1, success_);
        }
        return size;
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += computeSerializedSize_0();
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.matcharena.grpc.v1.LeaveQueueResponse)) {
            return super.equals(obj);
        }
        com.matcharena.grpc.v1.LeaveQueueResponse other = (com.matcharena.grpc.v1.LeaveQueueResponse) obj;

        if (getSuccess()
                != other.getSuccess()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getSuccess());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeaveQueueResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.LeaveQueueResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code match_arena.v1.LeaveQueueResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:match_arena.v1.LeaveQueueResponse)
            com.matcharena.grpc.v1.LeaveQueueResponseOrBuilder {
        private int bitField0_;
        private boolean success_;

        // Construct using com.matcharena.grpc.v1.LeaveQueueResponse.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.matcharena.grpc.v1.LeaveQueueResponse.class, com.matcharena.grpc.v1.LeaveQueueResponse.Builder.class);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            success_ = false;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.matcharena.grpc.v1.Matchmaking.internal_static_match_arena_v1_LeaveQueueResponse_descriptor;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.LeaveQueueResponse getDefaultInstanceForType() {
            return com.matcharena.grpc.v1.LeaveQueueResponse.getDefaultInstance();
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.LeaveQueueResponse build() {
            com.matcharena.grpc.v1.LeaveQueueResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.LeaveQueueResponse buildPartial() {
            com.matcharena.grpc.v1.LeaveQueueResponse result = new com.matcharena.grpc.v1.LeaveQueueResponse(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(com.matcharena.grpc.v1.LeaveQueueResponse result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.success_ = success_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.matcharena.grpc.v1.LeaveQueueResponse) {
                return mergeFrom((com.matcharena.grpc.v1.LeaveQueueResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.matcharena.grpc.v1.LeaveQueueResponse other) {
            if (other == com.matcharena.grpc.v1.LeaveQueueResponse.getDefaultInstance()) return this;
            if (other.getSuccess() != false) {
                setSuccess(other.getSuccess());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            success_ = input.readBool();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>bool success = 1 [json_name = "success"];</code>
         *
         * @return The success.
         */
        @java.lang.Override
        public boolean getSuccess() {
            return success_;
        }

        /**
         * <code>bool success = 1 [json_name = "success"];</code>
         *
         * @param value The success to set.
         * @return This builder for chaining.
         */
        public Builder setSuccess(boolean value) {

            success_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>bool success = 1 [json_name = "success"];</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSuccess() {
            bitField0_ = (bitField0_ & ~0x00000001);
            success_ = false;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:match_arena.v1.LeaveQueueResponse)
    }

}

