// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/matchmaking.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

@com.google.protobuf.Generated
public interface MatchFoundOrBuilder extends
        // @@protoc_insertion_point(interface_extends:match_arena.v1.MatchFound)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     *
     * @return The sessionId.
     */
    java.lang.String getSessionId();

    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     *
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
    getSessionIdBytes();

    /**
     * <code>repeated string player_ids = 2 [json_name = "playerIds"];</code>
     *
     * @return A list containing the playerIds.
     */
    java.util.List<java.lang.String>
    getPlayerIdsList();

    /**
     * <code>repeated string player_ids = 2 [json_name = "playerIds"];</code>
     *
     * @return The count of playerIds.
     */
    int getPlayerIdsCount();

    /**
     * <code>repeated string player_ids = 2 [json_name = "playerIds"];</code>
     *
     * @param index The index of the element to return.
     * @return The playerIds at the given index.
     */
    java.lang.String getPlayerIds(int index);

    /**
     * <code>repeated string player_ids = 2 [json_name = "playerIds"];</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the playerIds at the given index.
     */
    com.google.protobuf.ByteString
    getPlayerIdsBytes(int index);
}
