// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/matchmaking.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

@com.google.protobuf.Generated
public final class Matchmaking extends com.google.protobuf.GeneratedFile {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_JoinQueueRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_JoinQueueRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_MatchFound_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_MatchFound_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_JoinQueueUpdate_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_JoinQueueUpdate_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_LeaveQueueRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_LeaveQueueRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_match_arena_v1_LeaveQueueResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_match_arena_v1_LeaveQueueResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 35,
                /* patch= */ 1,
                /* suffix= */ "",
                "Matchmaking");
    }

    static {
        java.lang.String[] descriptorData = {
                "\n match_arena/v1/matchmaking.proto\022\016matc" +
                        "h_arena.v1\"G\n\020JoinQueueRequest\022\033\n\tplayer" +
                        "_id\030\001 \001(\tR\010playerId\022\026\n\006rating\030\002 \001(\005R\006rat" +
                        "ing\"J\n\nMatchFound\022\035\n\nsession_id\030\001 \001(\tR\ts" +
                        "essionId\022\035\n\nplayer_ids\030\002 \003(\tR\tplayerIds\"" +
                        "\204\001\n\017JoinQueueUpdate\022(\n\017queue_ticket_id\030\001" +
                        " \001(\tH\000R\rqueueTicketId\022=\n\013match_found\030\002 \001" +
                        "(\0132\032.match_arena.v1.MatchFoundH\000R\nmatchF" +
                        "oundB\010\n\006update\";\n\021LeaveQueueRequest\022&\n\017q" +
                        "ueue_ticket_id\030\001 \001(\tR\rqueueTicketId\".\n\022L" +
                        "eaveQueueResponse\022\030\n\007success\030\001 \001(\010R\007succ" +
                        "ess2\273\001\n\022MatchmakingService\022P\n\tJoinQueue\022" +
                        " .match_arena.v1.JoinQueueRequest\032\037.matc" +
                        "h_arena.v1.JoinQueueUpdate0\001\022S\n\nLeaveQue" +
                        "ue\022!.match_arena.v1.LeaveQueueRequest\032\"." +
                        "match_arena.v1.LeaveQueueResponseBt\n\026com" +
                        ".matcharena.grpc.v1P\001ZXgithub.com/ihsang" +
                        "uldur/match-arena/game-service/internal/" +
                        "gen/match_arena/v1;matcharenav1b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_match_arena_v1_JoinQueueRequest_descriptor =
                getDescriptor().getMessageType(0);
        internal_static_match_arena_v1_JoinQueueRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_JoinQueueRequest_descriptor,
                new java.lang.String[]{"PlayerId", "Rating",});
        internal_static_match_arena_v1_MatchFound_descriptor =
                getDescriptor().getMessageType(1);
        internal_static_match_arena_v1_MatchFound_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_MatchFound_descriptor,
                new java.lang.String[]{"SessionId", "PlayerIds",});
        internal_static_match_arena_v1_JoinQueueUpdate_descriptor =
                getDescriptor().getMessageType(2);
        internal_static_match_arena_v1_JoinQueueUpdate_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_JoinQueueUpdate_descriptor,
                new java.lang.String[]{"QueueTicketId", "MatchFound", "Update",});
        internal_static_match_arena_v1_LeaveQueueRequest_descriptor =
                getDescriptor().getMessageType(3);
        internal_static_match_arena_v1_LeaveQueueRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_LeaveQueueRequest_descriptor,
                new java.lang.String[]{"QueueTicketId",});
        internal_static_match_arena_v1_LeaveQueueResponse_descriptor =
                getDescriptor().getMessageType(4);
        internal_static_match_arena_v1_LeaveQueueResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_match_arena_v1_LeaveQueueResponse_descriptor,
                new java.lang.String[]{"Success",});
        descriptor.resolveAllFeaturesImmutable();
    }
    private Matchmaking() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
