// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/account.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

@com.google.protobuf.Generated
public interface PingResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:match_arena.v1.PingResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1 [json_name = "message"];</code>
     *
     * @return The message.
     */
    java.lang.String getMessage();

    /**
     * <code>string message = 1 [json_name = "message"];</code>
     *
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
    getMessageBytes();
}
