// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/game_session.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

@com.google.protobuf.Generated
public interface PlayerScoreOrBuilder extends
    // @@protoc_insertion_point(interface_extends:match_arena.v1.PlayerScore)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string player_id = 1 [json_name = "playerId"];</code>
   * @return The playerId.
   */
  java.lang.String getPlayerId();
  /**
   * <code>string player_id = 1 [json_name = "playerId"];</code>
   * @return The bytes for playerId.
   */
  com.google.protobuf.ByteString
      getPlayerIdBytes();

  /**
   * <code>int32 score = 2 [json_name = "score"];</code>
   * @return The score.
   */
  int getScore();
}
