// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/account.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

@com.google.protobuf.Generated
public interface ReportMatchResultRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:match_arena.v1.ReportMatchResultRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     *
     * @return The sessionId.
     */
    java.lang.String getSessionId();

    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     *
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
    getSessionIdBytes();
}
