// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/account.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

/**
 * Protobuf type {@code match_arena.v1.ReportMatchResultRequest}
 */
@com.google.protobuf.Generated
public final class ReportMatchResultRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:match_arena.v1.ReportMatchResultRequest)
        ReportMatchResultRequestOrBuilder {
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    public static final int PARTICIPANTS_FIELD_NUMBER = 2;
    public static final int PLAYED_AT_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:match_arena.v1.ReportMatchResultRequest)
    private static final com.matcharena.grpc.v1.ReportMatchResultRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<ReportMatchResultRequest>
            PARSER = new com.google.protobuf.AbstractParser<ReportMatchResultRequest>() {
        @java.lang.Override
        public ReportMatchResultRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 35,
                /* patch= */ 1,
                /* suffix= */ "",
                "ReportMatchResultRequest");
    }

    static {
        DEFAULT_INSTANCE = new com.matcharena.grpc.v1.ReportMatchResultRequest();
    }

    private int bitField0_;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sessionId_ = "";
    @SuppressWarnings("serial")
    private java.util.List<com.matcharena.grpc.v1.MatchParticipant> participants_;
    private com.google.protobuf.Timestamp playedAt_;
    private byte memoizedIsInitialized = -1;
    // Use ReportMatchResultRequest.newBuilder() to construct.
    private ReportMatchResultRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ReportMatchResultRequest() {
        sessionId_ = "";
        participants_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.matcharena.grpc.v1.Account.internal_static_match_arena_v1_ReportMatchResultRequest_descriptor;
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.matcharena.grpc.v1.ReportMatchResultRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.matcharena.grpc.v1.ReportMatchResultRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<ReportMatchResultRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.matcharena.grpc.v1.Account.internal_static_match_arena_v1_ReportMatchResultRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.matcharena.grpc.v1.Account.internal_static_match_arena_v1_ReportMatchResultRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.matcharena.grpc.v1.ReportMatchResultRequest.class, com.matcharena.grpc.v1.ReportMatchResultRequest.Builder.class);
    }

    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     *
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            sessionId_ = s;
            return s;
        }
    }

    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     *
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            sessionId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
     */
    @java.lang.Override
    public java.util.List<com.matcharena.grpc.v1.MatchParticipant> getParticipantsList() {
        return participants_;
    }

    /**
     * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.matcharena.grpc.v1.MatchParticipantOrBuilder>
    getParticipantsOrBuilderList() {
        return participants_;
    }

    /**
     * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
     */
    @java.lang.Override
    public int getParticipantsCount() {
        return participants_.size();
    }

    /**
     * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
     */
    @java.lang.Override
    public com.matcharena.grpc.v1.MatchParticipant getParticipants(int index) {
        return participants_.get(index);
    }

    /**
     * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
     */
    @java.lang.Override
    public com.matcharena.grpc.v1.MatchParticipantOrBuilder getParticipantsOrBuilder(
            int index) {
        return participants_.get(index);
    }

    /**
     * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
     *
     * @return Whether the playedAt field is set.
     */
    @java.lang.Override
    public boolean hasPlayedAt() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
     *
     * @return The playedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getPlayedAt() {
        return playedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : playedAt_;
    }

    /**
     * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getPlayedAtOrBuilder() {
        return playedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : playedAt_;
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
        }
        for (int i = 0; i < participants_.size(); i++) {
            output.writeMessage(2, participants_.get(i));
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            output.writeMessage(3, getPlayedAt());
        }
        getUnknownFields().writeTo(output);
    }

    private int computeSerializedSize_0() {
        int size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
        }

        {
            final int count = participants_.size();
            for (int i = 0; i < count; i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSizeNoTag(participants_.get(i));
            }
            size += 1 * count;
        }
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, getPlayedAt());
        }
        return size;
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        size += computeSerializedSize_0();
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.matcharena.grpc.v1.ReportMatchResultRequest)) {
            return super.equals(obj);
        }
        com.matcharena.grpc.v1.ReportMatchResultRequest other = (com.matcharena.grpc.v1.ReportMatchResultRequest) obj;

        if (!getSessionId()
                .equals(other.getSessionId())) return false;
        if (!getParticipantsList()
                .equals(other.getParticipantsList())) return false;
        if (hasPlayedAt() != other.hasPlayedAt()) return false;
        if (hasPlayedAt()) {
            if (!getPlayedAt()
                    .equals(other.getPlayedAt())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSessionId().hashCode();
        if (getParticipantsCount() > 0) {
            hash = (37 * hash) + PARTICIPANTS_FIELD_NUMBER;
            hash = (53 * hash) + getParticipantsList().hashCode();
        }
        if (hasPlayedAt()) {
            hash = (37 * hash) + PLAYED_AT_FIELD_NUMBER;
            hash = (53 * hash) + getPlayedAt().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReportMatchResultRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.ReportMatchResultRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code match_arena.v1.ReportMatchResultRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:match_arena.v1.ReportMatchResultRequest)
            com.matcharena.grpc.v1.ReportMatchResultRequestOrBuilder {
        private int bitField0_;
        private java.lang.Object sessionId_ = "";
        private java.util.List<com.matcharena.grpc.v1.MatchParticipant> participants_ =
                java.util.Collections.emptyList();
        private com.google.protobuf.RepeatedFieldBuilder<
                com.matcharena.grpc.v1.MatchParticipant, com.matcharena.grpc.v1.MatchParticipant.Builder, com.matcharena.grpc.v1.MatchParticipantOrBuilder> participantsBuilder_;
        private com.google.protobuf.Timestamp playedAt_;
        private com.google.protobuf.SingleFieldBuilder<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> playedAtBuilder_;

        // Construct using com.matcharena.grpc.v1.ReportMatchResultRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.matcharena.grpc.v1.Account.internal_static_match_arena_v1_ReportMatchResultRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.matcharena.grpc.v1.Account.internal_static_match_arena_v1_ReportMatchResultRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.matcharena.grpc.v1.ReportMatchResultRequest.class, com.matcharena.grpc.v1.ReportMatchResultRequest.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage
                    .alwaysUseFieldBuilders) {
                internalGetParticipantsFieldBuilder();
                internalGetPlayedAtFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            sessionId_ = "";
            if (participantsBuilder_ == null) {
                participants_ = java.util.Collections.emptyList();
            } else {
                participants_ = null;
                participantsBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000002);
            playedAt_ = null;
            if (playedAtBuilder_ != null) {
                playedAtBuilder_.dispose();
                playedAtBuilder_ = null;
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.matcharena.grpc.v1.Account.internal_static_match_arena_v1_ReportMatchResultRequest_descriptor;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.ReportMatchResultRequest getDefaultInstanceForType() {
            return com.matcharena.grpc.v1.ReportMatchResultRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.ReportMatchResultRequest build() {
            com.matcharena.grpc.v1.ReportMatchResultRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.matcharena.grpc.v1.ReportMatchResultRequest buildPartial() {
            com.matcharena.grpc.v1.ReportMatchResultRequest result = new com.matcharena.grpc.v1.ReportMatchResultRequest(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(com.matcharena.grpc.v1.ReportMatchResultRequest result) {
            if (participantsBuilder_ == null) {
                if (((bitField0_ & 0x00000002) != 0)) {
                    participants_ = java.util.Collections.unmodifiableList(participants_);
                    bitField0_ = (bitField0_ & ~0x00000002);
                }
                result.participants_ = participants_;
            } else {
                result.participants_ = participantsBuilder_.build();
            }
        }

        private void buildPartial0(com.matcharena.grpc.v1.ReportMatchResultRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.sessionId_ = sessionId_;
            }
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.playedAt_ = playedAtBuilder_ == null
                        ? playedAt_
                        : playedAtBuilder_.build();
                to_bitField0_ |= 0x00000001;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.matcharena.grpc.v1.ReportMatchResultRequest) {
                return mergeFrom((com.matcharena.grpc.v1.ReportMatchResultRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.matcharena.grpc.v1.ReportMatchResultRequest other) {
            if (other == com.matcharena.grpc.v1.ReportMatchResultRequest.getDefaultInstance()) return this;
            if (!other.getSessionId().isEmpty()) {
                sessionId_ = other.sessionId_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (participantsBuilder_ == null) {
                if (!other.participants_.isEmpty()) {
                    if (participants_.isEmpty()) {
                        participants_ = other.participants_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                    } else {
                        ensureParticipantsIsMutable();
                        participants_.addAll(other.participants_);
                    }
                    onChanged();
                }
            } else {
                if (!other.participants_.isEmpty()) {
                    if (participantsBuilder_.isEmpty()) {
                        participantsBuilder_.dispose();
                        participantsBuilder_ = null;
                        participants_ = other.participants_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        participantsBuilder_ =
                                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                        internalGetParticipantsFieldBuilder() : null;
                    } else {
                        participantsBuilder_.addAllMessages(other.participants_);
                    }
                }
            }
            if (other.hasPlayedAt()) {
                mergePlayedAt(other.getPlayedAt());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            sessionId_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            com.matcharena.grpc.v1.MatchParticipant m =
                                    input.readMessage(
                                            com.matcharena.grpc.v1.MatchParticipant.parser(),
                                            extensionRegistry);
                            if (participantsBuilder_ == null) {
                                ensureParticipantsIsMutable();
                                participants_.add(m);
                            } else {
                                participantsBuilder_.addMessage(m);
                            }
                            break;
                        } // case 18
                        case 26: {
                            input.readMessage(
                                    internalGetPlayedAtFieldBuilder().getBuilder(),
                                    extensionRegistry);
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 26
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        /**
         * <code>string session_id = 1 [json_name = "sessionId"];</code>
         *
         * @return The sessionId.
         */
        public java.lang.String getSessionId() {
            java.lang.Object ref = sessionId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                sessionId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string session_id = 1 [json_name = "sessionId"];</code>
         *
         * @param value The sessionId to set.
         * @return This builder for chaining.
         */
        public Builder setSessionId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            sessionId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string session_id = 1 [json_name = "sessionId"];</code>
         *
         * @return The bytes for sessionId.
         */
        public com.google.protobuf.ByteString
        getSessionIdBytes() {
            java.lang.Object ref = sessionId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                sessionId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string session_id = 1 [json_name = "sessionId"];</code>
         *
         * @param value The bytes for sessionId to set.
         * @return This builder for chaining.
         */
        public Builder setSessionIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            sessionId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>string session_id = 1 [json_name = "sessionId"];</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSessionId() {
            sessionId_ = getDefaultInstance().getSessionId();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        private void ensureParticipantsIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                participants_ = new java.util.ArrayList<com.matcharena.grpc.v1.MatchParticipant>(participants_);
                bitField0_ |= 0x00000002;
            }
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public java.util.List<com.matcharena.grpc.v1.MatchParticipant> getParticipantsList() {
            if (participantsBuilder_ == null) {
                return java.util.Collections.unmodifiableList(participants_);
            } else {
                return participantsBuilder_.getMessageList();
            }
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public int getParticipantsCount() {
            if (participantsBuilder_ == null) {
                return participants_.size();
            } else {
                return participantsBuilder_.getCount();
            }
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public com.matcharena.grpc.v1.MatchParticipant getParticipants(int index) {
            if (participantsBuilder_ == null) {
                return participants_.get(index);
            } else {
                return participantsBuilder_.getMessage(index);
            }
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder setParticipants(
                int index, com.matcharena.grpc.v1.MatchParticipant value) {
            if (participantsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParticipantsIsMutable();
                participants_.set(index, value);
                onChanged();
            } else {
                participantsBuilder_.setMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder setParticipants(
                int index, com.matcharena.grpc.v1.MatchParticipant.Builder builderForValue) {
            if (participantsBuilder_ == null) {
                ensureParticipantsIsMutable();
                participants_.set(index, builderForValue.build());
                onChanged();
            } else {
                participantsBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder addParticipants(com.matcharena.grpc.v1.MatchParticipant value) {
            if (participantsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParticipantsIsMutable();
                participants_.add(value);
                onChanged();
            } else {
                participantsBuilder_.addMessage(value);
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder addParticipants(
                int index, com.matcharena.grpc.v1.MatchParticipant value) {
            if (participantsBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureParticipantsIsMutable();
                participants_.add(index, value);
                onChanged();
            } else {
                participantsBuilder_.addMessage(index, value);
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder addParticipants(
                com.matcharena.grpc.v1.MatchParticipant.Builder builderForValue) {
            if (participantsBuilder_ == null) {
                ensureParticipantsIsMutable();
                participants_.add(builderForValue.build());
                onChanged();
            } else {
                participantsBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder addParticipants(
                int index, com.matcharena.grpc.v1.MatchParticipant.Builder builderForValue) {
            if (participantsBuilder_ == null) {
                ensureParticipantsIsMutable();
                participants_.add(index, builderForValue.build());
                onChanged();
            } else {
                participantsBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder addAllParticipants(
                java.lang.Iterable<? extends com.matcharena.grpc.v1.MatchParticipant> values) {
            if (participantsBuilder_ == null) {
                ensureParticipantsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, participants_);
                onChanged();
            } else {
                participantsBuilder_.addAllMessages(values);
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder clearParticipants() {
            if (participantsBuilder_ == null) {
                participants_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
            } else {
                participantsBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public Builder removeParticipants(int index) {
            if (participantsBuilder_ == null) {
                ensureParticipantsIsMutable();
                participants_.remove(index);
                onChanged();
            } else {
                participantsBuilder_.remove(index);
            }
            return this;
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public com.matcharena.grpc.v1.MatchParticipant.Builder getParticipantsBuilder(
                int index) {
            return internalGetParticipantsFieldBuilder().getBuilder(index);
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public com.matcharena.grpc.v1.MatchParticipantOrBuilder getParticipantsOrBuilder(
                int index) {
            if (participantsBuilder_ == null) {
                return participants_.get(index);
            } else {
                return participantsBuilder_.getMessageOrBuilder(index);
            }
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public java.util.List<? extends com.matcharena.grpc.v1.MatchParticipantOrBuilder>
        getParticipantsOrBuilderList() {
            if (participantsBuilder_ != null) {
                return participantsBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(participants_);
            }
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public com.matcharena.grpc.v1.MatchParticipant.Builder addParticipantsBuilder() {
            return internalGetParticipantsFieldBuilder().addBuilder(
                    com.matcharena.grpc.v1.MatchParticipant.getDefaultInstance());
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public com.matcharena.grpc.v1.MatchParticipant.Builder addParticipantsBuilder(
                int index) {
            return internalGetParticipantsFieldBuilder().addBuilder(
                    index, com.matcharena.grpc.v1.MatchParticipant.getDefaultInstance());
        }

        /**
         * <code>repeated .match_arena.v1.MatchParticipant participants = 2 [json_name = "participants"];</code>
         */
        public java.util.List<com.matcharena.grpc.v1.MatchParticipant.Builder>
        getParticipantsBuilderList() {
            return internalGetParticipantsFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilder<
                com.matcharena.grpc.v1.MatchParticipant, com.matcharena.grpc.v1.MatchParticipant.Builder, com.matcharena.grpc.v1.MatchParticipantOrBuilder>
        internalGetParticipantsFieldBuilder() {
            if (participantsBuilder_ == null) {
                participantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                        com.matcharena.grpc.v1.MatchParticipant, com.matcharena.grpc.v1.MatchParticipant.Builder, com.matcharena.grpc.v1.MatchParticipantOrBuilder>(
                        participants_,
                        ((bitField0_ & 0x00000002) != 0),
                        getParentForChildren(),
                        isClean());
                participants_ = null;
            }
            return participantsBuilder_;
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         *
         * @return Whether the playedAt field is set.
         */
        public boolean hasPlayedAt() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         *
         * @return The playedAt.
         */
        public com.google.protobuf.Timestamp getPlayedAt() {
            if (playedAtBuilder_ == null) {
                return playedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : playedAt_;
            } else {
                return playedAtBuilder_.getMessage();
            }
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         */
        public Builder setPlayedAt(com.google.protobuf.Timestamp value) {
            if (playedAtBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                playedAt_ = value;
            } else {
                playedAtBuilder_.setMessage(value);
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         */
        public Builder setPlayedAt(
                com.google.protobuf.Timestamp.Builder builderForValue) {
            if (playedAtBuilder_ == null) {
                playedAt_ = builderForValue.build();
            } else {
                playedAtBuilder_.setMessage(builderForValue.build());
            }
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         */
        public Builder mergePlayedAt(com.google.protobuf.Timestamp value) {
            if (playedAtBuilder_ == null) {
                if (((bitField0_ & 0x00000004) != 0) &&
                        playedAt_ != null &&
                        playedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
                    getPlayedAtBuilder().mergeFrom(value);
                } else {
                    playedAt_ = value;
                }
            } else {
                playedAtBuilder_.mergeFrom(value);
            }
            if (playedAt_ != null) {
                bitField0_ |= 0x00000004;
                onChanged();
            }
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         */
        public Builder clearPlayedAt() {
            bitField0_ = (bitField0_ & ~0x00000004);
            playedAt_ = null;
            if (playedAtBuilder_ != null) {
                playedAtBuilder_.dispose();
                playedAtBuilder_ = null;
            }
            onChanged();
            return this;
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         */
        public com.google.protobuf.Timestamp.Builder getPlayedAtBuilder() {
            bitField0_ |= 0x00000004;
            onChanged();
            return internalGetPlayedAtFieldBuilder().getBuilder();
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         */
        public com.google.protobuf.TimestampOrBuilder getPlayedAtOrBuilder() {
            if (playedAtBuilder_ != null) {
                return playedAtBuilder_.getMessageOrBuilder();
            } else {
                return playedAt_ == null ?
                        com.google.protobuf.Timestamp.getDefaultInstance() : playedAt_;
            }
        }

        /**
         * <code>.google.protobuf.Timestamp played_at = 3 [json_name = "playedAt"];</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
                com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        internalGetPlayedAtFieldBuilder() {
            if (playedAtBuilder_ == null) {
                playedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                        getPlayedAt(),
                        getParentForChildren(),
                        isClean());
                playedAt_ = null;
            }
            return playedAtBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:match_arena.v1.ReportMatchResultRequest)
    }

}

