// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: match_arena/v1/game_session.proto
// Protobuf Java Version: 4.35.1

package com.matcharena.grpc.v1;

/**
 * Protobuf type {@code match_arena.v1.SessionUpdate}
 */
@com.google.protobuf.Generated
public final class SessionUpdate extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:match_arena.v1.SessionUpdate)
    SessionUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "SessionUpdate");
  }
  // Use SessionUpdate.newBuilder() to construct.
  private SessionUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SessionUpdate() {
    sessionId_ = "";
    scores_ = java.util.Collections.emptyList();
    flags_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.matcharena.grpc.v1.GameSession.internal_static_match_arena_v1_SessionUpdate_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.matcharena.grpc.v1.GameSession.internal_static_match_arena_v1_SessionUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.matcharena.grpc.v1.GameSession.internal_static_match_arena_v1_SessionUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.matcharena.grpc.v1.SessionUpdate.class, com.matcharena.grpc.v1.SessionUpdate.Builder.class);
  }

  public static final int SESSION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sessionId_ = "";
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public java.lang.String getSessionId() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionId_ = s;
      return s;
    }
  }
  /**
   * <code>string session_id = 1 [json_name = "sessionId"];</code>
   * @return The bytes for sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionIdBytes() {
    java.lang.Object ref = sessionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCORES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.matcharena.grpc.v1.PlayerScore> scores_;
  /**
   * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
   */
  @java.lang.Override
  public java.util.List<com.matcharena.grpc.v1.PlayerScore> getScoresList() {
    return scores_;
  }
  /**
   * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.matcharena.grpc.v1.PlayerScoreOrBuilder> 
      getScoresOrBuilderList() {
    return scores_;
  }
  /**
   * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
   */
  @java.lang.Override
  public int getScoresCount() {
    return scores_.size();
  }
  /**
   * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
   */
  @java.lang.Override
  public com.matcharena.grpc.v1.PlayerScore getScores(int index) {
    return scores_.get(index);
  }
  /**
   * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
   */
  @java.lang.Override
  public com.matcharena.grpc.v1.PlayerScoreOrBuilder getScoresOrBuilder(
      int index) {
    return scores_.get(index);
  }

  public static final int FLAGS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.matcharena.grpc.v1.AntiCheatFlag> flags_;
  /**
   * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
   */
  @java.lang.Override
  public java.util.List<com.matcharena.grpc.v1.AntiCheatFlag> getFlagsList() {
    return flags_;
  }
  /**
   * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.matcharena.grpc.v1.AntiCheatFlagOrBuilder> 
      getFlagsOrBuilderList() {
    return flags_;
  }
  /**
   * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
   */
  @java.lang.Override
  public int getFlagsCount() {
    return flags_.size();
  }
  /**
   * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
   */
  @java.lang.Override
  public com.matcharena.grpc.v1.AntiCheatFlag getFlags(int index) {
    return flags_.get(index);
  }
  /**
   * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
   */
  @java.lang.Override
  public com.matcharena.grpc.v1.AntiCheatFlagOrBuilder getFlagsOrBuilder(
      int index) {
    return flags_.get(index);
  }

  public static final int SESSION_ENDED_FIELD_NUMBER = 4;
  private boolean sessionEnded_ = false;
  /**
   * <code>bool session_ended = 4 [json_name = "sessionEnded"];</code>
   * @return The sessionEnded.
   */
  @java.lang.Override
  public boolean getSessionEnded() {
    return sessionEnded_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sessionId_);
    }
    for (int i = 0; i < scores_.size(); i++) {
      output.writeMessage(2, scores_.get(i));
    }
    for (int i = 0; i < flags_.size(); i++) {
      output.writeMessage(3, flags_.get(i));
    }
    if (sessionEnded_ != false) {
      output.writeBool(4, sessionEnded_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sessionId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sessionId_);
    }

        {
          final int count = scores_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(scores_.get(i));
          }
          size += 1 * count;
        }

        {
          final int count = flags_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(flags_.get(i));
          }
          size += 1 * count;
        }
    if (sessionEnded_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, sessionEnded_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.matcharena.grpc.v1.SessionUpdate)) {
      return super.equals(obj);
    }
    com.matcharena.grpc.v1.SessionUpdate other = (com.matcharena.grpc.v1.SessionUpdate) obj;

    if (!getSessionId()
        .equals(other.getSessionId())) return false;
    if (!getScoresList()
        .equals(other.getScoresList())) return false;
    if (!getFlagsList()
        .equals(other.getFlagsList())) return false;
    if (getSessionEnded()
        != other.getSessionEnded()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSessionId().hashCode();
    if (getScoresCount() > 0) {
      hash = (37 * hash) + SCORES_FIELD_NUMBER;
      hash = (53 * hash) + getScoresList().hashCode();
    }
    if (getFlagsCount() > 0) {
      hash = (37 * hash) + FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + getFlagsList().hashCode();
    }
    hash = (37 * hash) + SESSION_ENDED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSessionEnded());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.matcharena.grpc.v1.SessionUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.matcharena.grpc.v1.SessionUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.matcharena.grpc.v1.SessionUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.matcharena.grpc.v1.SessionUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code match_arena.v1.SessionUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:match_arena.v1.SessionUpdate)
      com.matcharena.grpc.v1.SessionUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.matcharena.grpc.v1.GameSession.internal_static_match_arena_v1_SessionUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.matcharena.grpc.v1.GameSession.internal_static_match_arena_v1_SessionUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.matcharena.grpc.v1.SessionUpdate.class, com.matcharena.grpc.v1.SessionUpdate.Builder.class);
    }

    // Construct using com.matcharena.grpc.v1.SessionUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sessionId_ = "";
      if (scoresBuilder_ == null) {
        scores_ = java.util.Collections.emptyList();
      } else {
        scores_ = null;
        scoresBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (flagsBuilder_ == null) {
        flags_ = java.util.Collections.emptyList();
      } else {
        flags_ = null;
        flagsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      sessionEnded_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.matcharena.grpc.v1.GameSession.internal_static_match_arena_v1_SessionUpdate_descriptor;
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.SessionUpdate getDefaultInstanceForType() {
      return com.matcharena.grpc.v1.SessionUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.SessionUpdate build() {
      com.matcharena.grpc.v1.SessionUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.matcharena.grpc.v1.SessionUpdate buildPartial() {
      com.matcharena.grpc.v1.SessionUpdate result = new com.matcharena.grpc.v1.SessionUpdate(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.matcharena.grpc.v1.SessionUpdate result) {
      if (scoresBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.scores_ = scores_;
      } else {
        result.scores_ = scoresBuilder_.build();
      }
      if (flagsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          flags_ = java.util.Collections.unmodifiableList(flags_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.flags_ = flags_;
      } else {
        result.flags_ = flagsBuilder_.build();
      }
    }

    private void buildPartial0(com.matcharena.grpc.v1.SessionUpdate result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sessionId_ = sessionId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sessionEnded_ = sessionEnded_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.matcharena.grpc.v1.SessionUpdate) {
        return mergeFrom((com.matcharena.grpc.v1.SessionUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.matcharena.grpc.v1.SessionUpdate other) {
      if (other == com.matcharena.grpc.v1.SessionUpdate.getDefaultInstance()) return this;
      if (!other.getSessionId().isEmpty()) {
        sessionId_ = other.sessionId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (scoresBuilder_ == null) {
        if (!other.scores_.isEmpty()) {
          if (scores_.isEmpty()) {
            scores_ = other.scores_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureScoresIsMutable();
            scores_.addAll(other.scores_);
          }
          onChanged();
        }
      } else {
        if (!other.scores_.isEmpty()) {
          if (scoresBuilder_.isEmpty()) {
            scoresBuilder_.dispose();
            scoresBuilder_ = null;
            scores_ = other.scores_;
            bitField0_ = (bitField0_ & ~0x00000002);
            scoresBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetScoresFieldBuilder() : null;
          } else {
            scoresBuilder_.addAllMessages(other.scores_);
          }
        }
      }
      if (flagsBuilder_ == null) {
        if (!other.flags_.isEmpty()) {
          if (flags_.isEmpty()) {
            flags_ = other.flags_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFlagsIsMutable();
            flags_.addAll(other.flags_);
          }
          onChanged();
        }
      } else {
        if (!other.flags_.isEmpty()) {
          if (flagsBuilder_.isEmpty()) {
            flagsBuilder_.dispose();
            flagsBuilder_ = null;
            flags_ = other.flags_;
            bitField0_ = (bitField0_ & ~0x00000004);
            flagsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetFlagsFieldBuilder() : null;
          } else {
            flagsBuilder_.addAllMessages(other.flags_);
          }
        }
      }
      if (other.getSessionEnded() != false) {
        setSessionEnded(other.getSessionEnded());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sessionId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.matcharena.grpc.v1.PlayerScore m =
                  input.readMessage(
                      com.matcharena.grpc.v1.PlayerScore.parser(),
                      extensionRegistry);
              if (scoresBuilder_ == null) {
                ensureScoresIsMutable();
                scores_.add(m);
              } else {
                scoresBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.matcharena.grpc.v1.AntiCheatFlag m =
                  input.readMessage(
                      com.matcharena.grpc.v1.AntiCheatFlag.parser(),
                      extensionRegistry);
              if (flagsBuilder_ == null) {
                ensureFlagsIsMutable();
                flags_.add(m);
              } else {
                flagsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 32: {
              sessionEnded_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sessionId_ = "";
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The sessionId.
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return The bytes for sessionId.
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      sessionId_ = getDefaultInstance().getSessionId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string session_id = 1 [json_name = "sessionId"];</code>
     * @param value The bytes for sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sessionId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.matcharena.grpc.v1.PlayerScore> scores_ =
      java.util.Collections.emptyList();
    private void ensureScoresIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        scores_ = new java.util.ArrayList<com.matcharena.grpc.v1.PlayerScore>(scores_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.matcharena.grpc.v1.PlayerScore, com.matcharena.grpc.v1.PlayerScore.Builder, com.matcharena.grpc.v1.PlayerScoreOrBuilder> scoresBuilder_;

    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public java.util.List<com.matcharena.grpc.v1.PlayerScore> getScoresList() {
      if (scoresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(scores_);
      } else {
        return scoresBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public int getScoresCount() {
      if (scoresBuilder_ == null) {
        return scores_.size();
      } else {
        return scoresBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public com.matcharena.grpc.v1.PlayerScore getScores(int index) {
      if (scoresBuilder_ == null) {
        return scores_.get(index);
      } else {
        return scoresBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder setScores(
        int index, com.matcharena.grpc.v1.PlayerScore value) {
      if (scoresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScoresIsMutable();
        scores_.set(index, value);
        onChanged();
      } else {
        scoresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder setScores(
        int index, com.matcharena.grpc.v1.PlayerScore.Builder builderForValue) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.set(index, builderForValue.build());
        onChanged();
      } else {
        scoresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder addScores(com.matcharena.grpc.v1.PlayerScore value) {
      if (scoresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScoresIsMutable();
        scores_.add(value);
        onChanged();
      } else {
        scoresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder addScores(
        int index, com.matcharena.grpc.v1.PlayerScore value) {
      if (scoresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScoresIsMutable();
        scores_.add(index, value);
        onChanged();
      } else {
        scoresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder addScores(
        com.matcharena.grpc.v1.PlayerScore.Builder builderForValue) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.add(builderForValue.build());
        onChanged();
      } else {
        scoresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder addScores(
        int index, com.matcharena.grpc.v1.PlayerScore.Builder builderForValue) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.add(index, builderForValue.build());
        onChanged();
      } else {
        scoresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder addAllScores(
        java.lang.Iterable<? extends com.matcharena.grpc.v1.PlayerScore> values) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, scores_);
        onChanged();
      } else {
        scoresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder clearScores() {
      if (scoresBuilder_ == null) {
        scores_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        scoresBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public Builder removeScores(int index) {
      if (scoresBuilder_ == null) {
        ensureScoresIsMutable();
        scores_.remove(index);
        onChanged();
      } else {
        scoresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public com.matcharena.grpc.v1.PlayerScore.Builder getScoresBuilder(
        int index) {
      return internalGetScoresFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public com.matcharena.grpc.v1.PlayerScoreOrBuilder getScoresOrBuilder(
        int index) {
      if (scoresBuilder_ == null) {
        return scores_.get(index);  } else {
        return scoresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public java.util.List<? extends com.matcharena.grpc.v1.PlayerScoreOrBuilder> 
         getScoresOrBuilderList() {
      if (scoresBuilder_ != null) {
        return scoresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(scores_);
      }
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public com.matcharena.grpc.v1.PlayerScore.Builder addScoresBuilder() {
      return internalGetScoresFieldBuilder().addBuilder(
          com.matcharena.grpc.v1.PlayerScore.getDefaultInstance());
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public com.matcharena.grpc.v1.PlayerScore.Builder addScoresBuilder(
        int index) {
      return internalGetScoresFieldBuilder().addBuilder(
          index, com.matcharena.grpc.v1.PlayerScore.getDefaultInstance());
    }
    /**
     * <code>repeated .match_arena.v1.PlayerScore scores = 2 [json_name = "scores"];</code>
     */
    public java.util.List<com.matcharena.grpc.v1.PlayerScore.Builder> 
         getScoresBuilderList() {
      return internalGetScoresFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.matcharena.grpc.v1.PlayerScore, com.matcharena.grpc.v1.PlayerScore.Builder, com.matcharena.grpc.v1.PlayerScoreOrBuilder> 
        internalGetScoresFieldBuilder() {
      if (scoresBuilder_ == null) {
        scoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.matcharena.grpc.v1.PlayerScore, com.matcharena.grpc.v1.PlayerScore.Builder, com.matcharena.grpc.v1.PlayerScoreOrBuilder>(
                scores_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        scores_ = null;
      }
      return scoresBuilder_;
    }

    private java.util.List<com.matcharena.grpc.v1.AntiCheatFlag> flags_ =
      java.util.Collections.emptyList();
    private void ensureFlagsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        flags_ = new java.util.ArrayList<com.matcharena.grpc.v1.AntiCheatFlag>(flags_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.matcharena.grpc.v1.AntiCheatFlag, com.matcharena.grpc.v1.AntiCheatFlag.Builder, com.matcharena.grpc.v1.AntiCheatFlagOrBuilder> flagsBuilder_;

    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public java.util.List<com.matcharena.grpc.v1.AntiCheatFlag> getFlagsList() {
      if (flagsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(flags_);
      } else {
        return flagsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public int getFlagsCount() {
      if (flagsBuilder_ == null) {
        return flags_.size();
      } else {
        return flagsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public com.matcharena.grpc.v1.AntiCheatFlag getFlags(int index) {
      if (flagsBuilder_ == null) {
        return flags_.get(index);
      } else {
        return flagsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder setFlags(
        int index, com.matcharena.grpc.v1.AntiCheatFlag value) {
      if (flagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlagsIsMutable();
        flags_.set(index, value);
        onChanged();
      } else {
        flagsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder setFlags(
        int index, com.matcharena.grpc.v1.AntiCheatFlag.Builder builderForValue) {
      if (flagsBuilder_ == null) {
        ensureFlagsIsMutable();
        flags_.set(index, builderForValue.build());
        onChanged();
      } else {
        flagsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder addFlags(com.matcharena.grpc.v1.AntiCheatFlag value) {
      if (flagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlagsIsMutable();
        flags_.add(value);
        onChanged();
      } else {
        flagsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder addFlags(
        int index, com.matcharena.grpc.v1.AntiCheatFlag value) {
      if (flagsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFlagsIsMutable();
        flags_.add(index, value);
        onChanged();
      } else {
        flagsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder addFlags(
        com.matcharena.grpc.v1.AntiCheatFlag.Builder builderForValue) {
      if (flagsBuilder_ == null) {
        ensureFlagsIsMutable();
        flags_.add(builderForValue.build());
        onChanged();
      } else {
        flagsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder addFlags(
        int index, com.matcharena.grpc.v1.AntiCheatFlag.Builder builderForValue) {
      if (flagsBuilder_ == null) {
        ensureFlagsIsMutable();
        flags_.add(index, builderForValue.build());
        onChanged();
      } else {
        flagsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder addAllFlags(
        java.lang.Iterable<? extends com.matcharena.grpc.v1.AntiCheatFlag> values) {
      if (flagsBuilder_ == null) {
        ensureFlagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, flags_);
        onChanged();
      } else {
        flagsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder clearFlags() {
      if (flagsBuilder_ == null) {
        flags_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        flagsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public Builder removeFlags(int index) {
      if (flagsBuilder_ == null) {
        ensureFlagsIsMutable();
        flags_.remove(index);
        onChanged();
      } else {
        flagsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public com.matcharena.grpc.v1.AntiCheatFlag.Builder getFlagsBuilder(
        int index) {
      return internalGetFlagsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public com.matcharena.grpc.v1.AntiCheatFlagOrBuilder getFlagsOrBuilder(
        int index) {
      if (flagsBuilder_ == null) {
        return flags_.get(index);  } else {
        return flagsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public java.util.List<? extends com.matcharena.grpc.v1.AntiCheatFlagOrBuilder> 
         getFlagsOrBuilderList() {
      if (flagsBuilder_ != null) {
        return flagsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(flags_);
      }
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public com.matcharena.grpc.v1.AntiCheatFlag.Builder addFlagsBuilder() {
      return internalGetFlagsFieldBuilder().addBuilder(
          com.matcharena.grpc.v1.AntiCheatFlag.getDefaultInstance());
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public com.matcharena.grpc.v1.AntiCheatFlag.Builder addFlagsBuilder(
        int index) {
      return internalGetFlagsFieldBuilder().addBuilder(
          index, com.matcharena.grpc.v1.AntiCheatFlag.getDefaultInstance());
    }
    /**
     * <code>repeated .match_arena.v1.AntiCheatFlag flags = 3 [json_name = "flags"];</code>
     */
    public java.util.List<com.matcharena.grpc.v1.AntiCheatFlag.Builder> 
         getFlagsBuilderList() {
      return internalGetFlagsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.matcharena.grpc.v1.AntiCheatFlag, com.matcharena.grpc.v1.AntiCheatFlag.Builder, com.matcharena.grpc.v1.AntiCheatFlagOrBuilder> 
        internalGetFlagsFieldBuilder() {
      if (flagsBuilder_ == null) {
        flagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.matcharena.grpc.v1.AntiCheatFlag, com.matcharena.grpc.v1.AntiCheatFlag.Builder, com.matcharena.grpc.v1.AntiCheatFlagOrBuilder>(
                flags_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        flags_ = null;
      }
      return flagsBuilder_;
    }

    private boolean sessionEnded_ ;
    /**
     * <code>bool session_ended = 4 [json_name = "sessionEnded"];</code>
     * @return The sessionEnded.
     */
    @java.lang.Override
    public boolean getSessionEnded() {
      return sessionEnded_;
    }
    /**
     * <code>bool session_ended = 4 [json_name = "sessionEnded"];</code>
     * @param value The sessionEnded to set.
     * @return This builder for chaining.
     */
    public Builder setSessionEnded(boolean value) {

      sessionEnded_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool session_ended = 4 [json_name = "sessionEnded"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionEnded() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sessionEnded_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:match_arena.v1.SessionUpdate)
  }

  // @@protoc_insertion_point(class_scope:match_arena.v1.SessionUpdate)
  private static final com.matcharena.grpc.v1.SessionUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.matcharena.grpc.v1.SessionUpdate();
  }

  public static com.matcharena.grpc.v1.SessionUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SessionUpdate>
      PARSER = new com.google.protobuf.AbstractParser<SessionUpdate>() {
    @java.lang.Override
    public SessionUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SessionUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SessionUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.matcharena.grpc.v1.SessionUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

