# General
spring.application.name=account-service
server.servlet.context-path=/api

# gRPC
grpc.server.port=9090

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/match_arena
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JPA
spring.jpa.hibernate.ddl-auto=validate

# JWT
jwt.secret=${JWT_SECRET:change_this_key}
jwt.expiration-in-ms=86400000
